// Vehicle configuration
export const START_GET_VEHICLE_CONFIGURATION =
  "START_GET_VEHICLE_CONFIGURATION";
export const GET_VEHICLE_CONFIGURATION_SUCCESS =
  "GET_VEHICLE_CONFIGURATION_SUCCESS";
export const GET_VEHICLE_CONFIGURATION_FAILURE =
  "GET_VEHICLE_CONFIGURATION_FAILURE";
export const GET_VEHICLE_CONFIGURATION_FINISHED =
  "GET_VEHICLE_CONFIGURATION_FINISHED";

export const START_POST_VEHICLE_CONFIGURATION =
  "START_POST_VEHICLE_CONFIGURATION";
export const POST_VEHICLE_CONFIGURATION_SUCCESS =
  "POST_VEHICLE_CONFIGURATION_SUCCESS";
export const POST_VEHICLE_CONFIGURATION_FAILURE =
  "POST_VEHICLE_CONFIGURATION_FAILURE";
export const POST_VEHICLE_CONFIGURATION_FINISHED =
  "POST_VEHICLE_CONFIGURATION_FINISHED";
